FROM nginx
# USER root 
RUN useradd -ms /bin/bash jack
WORKDIR /home/

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./server.c  /home/server.c
COPY ./run.sh /home/run.sh

RUN apt update && apt install -y gcc spawn-fcgi libfcgi-dev
RUN apt update && apt install -y libfcgi-dev && apt install -y spawn-fcgi && apt install -y gcc; 
# WORKDIR /home/
RUN chown -R jack:jack /etc/nginx/nginx.conf && \
    chown -R jack:jack /var/cache/nginx && \
    chown -R jack:jack /home && \
    touch /var/run/nginx.pid && \
    chown -R jack:jack /var/run/nginx.pid ;\
    chmod +x ./run.sh && rm -rf /var/lib/apt/lists


USER jack

ENTRYPOINT ["./run.sh"]
HEALTHCHECK NONE