FROM nginx
USER root 

COPY nginx.conf /etc/nginx/nginx.conf
COPY server.c  ./
COPY run.sh ./

# RUN apt update && apt install -y gcc spawn-fcgi libfcgi-dev
RUN apt update && apt install -y libfcgi-dev && apt install -y spawn-fcgi && apt install -y gcc; \
    chmod +x ./run.sh && rm -rf /var/lib/apt/lists
# WORKDIR /home/

ENTRYPOINT ["./run.sh"]
