FROM nginx

WORKDIR /home/

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./run.sh ./run.sh

RUN apt update && apt install -y gcc spawn-fcgi libfcgi-dev
RUN apt update && apt install -y libfcgi-dev && apt install -y spawn-fcgi && apt install -y gcc; 
# WORKDIR /home/
RUN chown -R nginx:nginx /etc/nginx/nginx.conf && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /home && \
    touch /var/run/nginx.pid && \
    chown nginx:nginx /var/run/nginx.pid ;\
    chmod +x ./run.sh && rm -rf /var/lib/apt/lists

USER nginx

ENTRYPOINT ["./run.sh"]
HEALTHCHECK NONE

